version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "gomod"
    directory: "/tools/logdrkly"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/packages/javascript"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
